### ISSUE TITLE
problem: prices are denominated in USD

### ISSUE THREAD

**Issue by gazhayes** [znftmarket/problems#1]
problem: prices are denominated in USD, and listing fees are denominated in ETH.

Solution: denominate everything in BTC instead, at the contract level.

**Comment by sujithsomraaj** [comment]
@gazhayes can we handle BTC at the client level? SC oracles are not consistent for BTC

**Comment by ssomraaj** [comment]
migrated to BTC in the SC level and added two-level conversions in oracle. Updated the client application as well
