### ISSUE TITLE
Problem: auctions display a listing price, but it is not needed

### ISSUE THREAD

**Issue by gazhayes** [znftmarket/problems#10]
Problem: auctions display a listing price, but it is not needed

The starting price doesn't matter, only the current price.

**Comment by sujithsomraaj** [comment]
@gazhayes added the default price to 0, but the merchants can set a floor price if they wish to sell it at a floor price. Is that fine?

**Comment by sujithsomraaj** [comment]
Added displaying of only current price & an option to set floor price if merchant wishes or all auction starts at 0

**Comment by gazhayes** [comment]
Ok

**Comment by ssomraaj** [comment]
@gazhayes is this issue completed ? Is so please close it
