### ISSUE TITLE
problem: can't view merchant information

### ISSUE THREAD

**Issue by gazhayes** [znftmarket/problems#11]
problem: users can't view mechant information, they can only view the data on blockchain explorer which most of them don't care about anyway

**Comment by ssomraaj** [comment]
Added a page to view merchant Info /merchant/0x45743228d93c9ce6a8738a58e1d632f8270c12ac

Not styled. A basic info fetch from IPFS & Graph is implemented

**Comment by gazhayes** [comment]
can you update the UI so that the user can easily get to this page from the listing?

**Comment by sujithsomraaj** [comment]
it's already done @gazhayes

**Comment by sujithsomraaj** [comment]
https://main.dhlsn14g4sttf.amplifyapp.com/merchant/0x45743228d93c9ce6a8738a58e1d632f8270c12ac
