### ISSUE TITLE
problem: proposal vote metrics don't mean anything

### ISSUE THREAD

**Issue by gazhayes** [znftmarket/problems#2]
problem: proposal vote metrics don't mean anything

The votes are shown as a nominal value, which doesn't mean anything.

Solution: show votes as a percentage of total shares

<img width="827" alt="Screenshot 2021-06-25 at 12 45 04 PM" src="https://user-images.githubusercontent.com/8143945/123372176-afca4e00-d5b5-11eb-8202-503ce0e83d0c.png">

**Comment by ssomraaj** [comment]
Added showing vote percentage
