### ISSUE TITLE
problem: merchant registration doesn't include all required info

### ISSUE THREAD

**Issue by gazhayes** [znftmarket/problems#27]
problem: vendor registration doesn't include all required info

### Required information:
[x] Company name

[x] website

[ ] upload: business registration documents (images or pdf)

[ ] upload: Signed letter from the company director stating their public address (the BSC address used for registration, image or pdf)

[ ] field: contact email address for shareholders to ask questions about their application

[ ] field: Company description and history (<2000 words)

[ ] field: proposed types of products to list (<500 words)

[ ]social media proofs:
Generate a random hash (random number => sha256 hash) and take the first 8 characters of the hash. Display this to the user and also insert it into the SC/IPFS object.

Tell the user: "To connect your social media accounts, please post the following: We are registering to ZNFT Market, our unique code is xxxxxxxx. Copy and paste the link to the post below. Repeat this for any social media accounts you wish to add to your profile, add each link on a new line."

**Comment by ssomraaj** [comment]
Added all these fields to the Merchant Registration Process

**Comment by gazhayes** [comment]
The hash for social media proofs is not displayed to the user.

**Comment by ssomraaj** [comment]
it's shown @gazhayes
